# Generated by Django 4.0 on 2021-12-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sprint_result_alter_subobjective_objective_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='subobjective',
            name='Sprint',
        ),
        migrations.AddField(
            model_name='sprint',
            name='SubObjective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subobjective', to='core.subobjective'),
        ),
    ]
