# Generated by Django 4.0 on 2021-12-19 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_brand_user_brand_po_brand_scrum_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subobjective',
            name='Objective_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_objective', to='core.objective'),
        ),
        migrations.AlterField(
            model_name='subobjective',
            name='Sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_sub', to='core.sprint'),
        ),
    ]
