# Generated by Django 4.0 on 2021-12-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subobjective_objective_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cohort',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
